services:
  urlshortener.database:
    image: postgres:latest
    container_name: urlshortener.database
    environment:
      - POSTGRES_DB=UrlShortenerDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  urlshortener.api:
    image: ${DOCKER_REGISTRY-}urlshortener
    build:
      context: .
      dockerfile: ./UrlShortener.Api/Dockerfile
    ports:
      - 8080:8080
      - 8081:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  urlshortener.frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200

volumes:
  pgdata: